menu:
  首页: / # hexo new page index
  文章: /list/ # hexo new page list
  关于: /about/ # hexo new page about
  标签: /tags/ # hexo new page tags
  分类: /categories/ # hexo new page categories

showInMenu:
  - 文章
  - 关于
  - 标签
  - 分类

index:
  header:
    - "A.T.フィールド 全開！"
  hitokoto: false # 一言接口
  footer: Email:shaojunjie0912@outlook.com
  titlePosition: left # center | left  # 首页标题的位置

footerLink:
  info: © 2001-2024 ShaoJunjie
  联系: /contact/ # 需要hexo new page contact
  订阅: /subscribe/

post:
  footer: For Ayanami Rei! # 底部左侧 自定义信息
  themeInfo: false # true | false  # 是否开启 底部右侧 声明本站信息
  endContent: 以上 # 当你使用了 评论功能，此配置才会生效

favicon: /img/avatar.png

tool:
  darkMode: true # 暗黑模式
  returnToTop: true # 回到顶部按钮
  returnToLast: true # 回退页面按钮
  topToc: true # 文章顶部目录
  leftToc: true # 文章左侧目录 目前仅支持大屏幕浮现

# ---------------------------------------------------------------------------------------
# 以上为基本配置，实现了A4主题追求的纯净风
#
# 以下为 非必要不必更改的配置
#
# ps：还有经过A4作者测试，可供你使用的插件，详见：https://ninojay.top/tags/hexoPlugin/
# ---------------------------------------------------------------------------------------

# 你可能会用到的 https://ninojay.top/2023/website-cdn/
cdn:
  enable: false # 如果你修改了 css/js ，也许需要把cdn设置为false才会生效
  choose: jsdelivr # aliyun | unpkg| jsdelivr  # 都调整为利于国内的cdn，建议使用默认的 jsdelivr 即可
  # 因为是免费CDN，所以有挂的风险，一旦发现网站样式出现原来没有的问题，请尝试关闭CDN

# 实验性功能：A4色调调整：颜色搭配是很主观的行为
# 设置为 false 为 A4 默认灰白色调，可设置为 true 直接启动 体验下 另一种护眼预置色调
# 注：颜色代码需加“#”，颜色单词不需要加“#”
# 更多A4色调搭配推荐：https://ninojay.top/hexoplugin/A4-color-change/
color:
  enable: false # true | false
  font: "#9e5345" # 字体颜色
  background: "#e8e0c9" # 最底部层背景颜色
  indexBackGround: "#efeae2" # 首页层颜色
  postBackGround: "#efeae2" # 文章页层颜色
  codeBackGround: "#e8e0c9" # 代码块背景颜色
  codeFont: "#2e5041" # 代码块字体颜色
  linkBeforeClick: "#2e5041" # 链接点击前的颜色
  linkAfterClick: "#9c9caf" # 链接点击后的颜色

# A4背景引入图片
imageShow:
  enable: false
  background: /img/favicon.webp # 最底部层背景

font:
  enable: false # 是否使用字体开关功能
  LXGWWenKai: true

inject:
  css: css/custom.css

version: v1.8.9
